# Generated by Django 4.2.1 on 2023-05-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image_upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='User/')),
            ],
            options={
                'db_table': 'Image',
            },
        ),
    ]
